### ISSUE TITLE
Robot spins at full speed when in "slow" mode

### ISSUE THREAD

**Issue by jeff-o** [ros-teleop/teleop_twist_joy#11]
We noticed an issue on our Husky platform that the robot spins at full speed even while in "slow" mode.  This could lead to potentially dangerous situations where the operator is not expecting the robot to move so quickly - after all, they are probably driving in slow mode for a reason.

Our software engineers have determined that the problem lies in teleop_twist_joy; could you please take a look?  Thanks.

**Comment by mikepurvis** [comment]
Resolved by #12, but a corresponding update in Husky's teleop config will be necessary.
