### ISSUE TITLE
bug in teleop_twist_joy.cpp

### ISSUE THREAD

**Issue by leonhartyao** [ros-teleop/teleop_twist_joy#20]
in line 171 it should be "y".

**Comment by tonybaltovski** [comment]
It should be, good catch. Do you want to submit a pull request?

**Comment by leonhartyao** [comment]
... do it by ýourself, it' OK :)

2016-04-29 15:45 GMT+02:00 Tony Baltovski notifications@github.com:

> It should be, good catch. Do you want to submit a pull request?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ros-teleop/teleop_twist_joy/issues/20#issuecomment-215717022

## 

Mit freundlichen Grüßen | Best Regards!

Yao,Chao
Uhlandstr. 39  4.01L
01069 Dresden, Germany
+49 176 93217281
