### ISSUE TITLE
Release for Melodic

### ISSUE THREAD

**Issue by vincentrou** [ros-teleop/teleop_twist_joy#28]
I would be happy to help if needed.

**Comment by doisyg** [comment]
same here

**Comment by clalancette** [comment]
@mikepurvis This would be nice to have in Melodic.  Mind releasing it?

**Comment by mikepurvis** [comment]
Adding @vincentrou as maintainer to release Melodic. Please consider merging pending PRs before release.

**Comment by mikepurvis** [comment]
@tfoote I don't seem to have permissions to add @vincentrou to the new ros-gbp/teleop team. Can you take care of this, please? https://github.com/orgs/ros-gbp/teams/teleop

Vincent, you should at least have access now to merge PRs here— let's get the unit tests passing and then prepare the release, and then you can bloom it once you have write access to the GBP repo.

**Comment by vincentrou** [comment]
Thanks for adding me @mikepurvis but for now I cannot merge PR or push anything to the repo.
I think that I do not have the right permission. And yes the access to the release repo will help @tfoote  !

**Comment by clalancette** [comment]
@mikepurvis @vincentrou I just realized that I had power to do this, so I invited @vincentrou to this organization.  Let me know if that works.

**Comment by mikepurvis** [comment]
Blah, the github teams system is so confusing. @vincentrou please try now.

@clalancette Thanks for that, though I also just realised there was actually an existing team on ros-gbp, but I don't have permissions to it (sigh), so when you have a moment, please:

- add Vincent instead to here: https://github.com/orgs/ros-gbp/teams/ros-teleop/members
- and delete the one I created: https://github.com/orgs/ros-gbp/teams/teleop/edit

**Comment by clalancette** [comment]
@mikepurvis OK, I think I've done what you requested now.  @vincentrou sorry for the back-n-forth, you probably have multiple GitHub invitations now.  I'd suggest ignoring all but the last, and hopefully that will get you setup.

**Comment by vincentrou** [comment]
Thanks all. It will be released in the next sync.
