### ISSUE TITLE
Release for Noetic

### ISSUE THREAD

**Issue by Timple** [ros-teleop/teleop_twist_joy#37]
Would you mind releasing this package also for the newest distibution ROS Noetic? :)

**Comment by doisyg** [comment]
same here, would love to see it released. Compilation from src is okay

**Comment by Timple** [comment]
'joy' dependency hasn't been released yet :(

**Comment by vincentrou** [comment]
I no more use this repo. You can ask to @mikepurvis if you want to be added as maintainer and release it. There is a few PR to merge before.

**Comment by tonybaltovski** [comment]
I could also maintain this repo since it is used by nearly all the Clearpath robots.

**Comment by Achllle** [comment]
Also wondering why there's not kinetic track for this either.

**Comment by doisyg** [comment]
joy is now released

**Comment by Achllle** [comment]
Would also be happy to maintain and have experience releasing packages

**Comment by shawnk3** [comment]
any update of release for ros noetic?

**Comment by Tobias-Fischer** [comment]
+1

**Comment by bostoncleek** [comment]
Also willing to maintain and release

**Comment by Timple** [comment]
@mikepurvis can you appoint one or all of the above volunteers as maintainer to get this going?

**Comment by vincentrou** [comment]
I have made a pull request for noetic release https://github.com/ros/rosdistro/pull/26555
But I do not merge any pull request of the teleop_twist_joy repo and put it status to unmaintained.

We are still looking for someone to add one of volunteers as maintainer on this repo and the [release one](https://github.com/ros-gbp/teleop_twist_joy-release). Maybe one of you have the right ? @bmagyar @tfoote @trainman419 @efernandez

**Comment by efernandez** [comment]
I've added @tonybaltovski to the ros-teleop **Maintainers** team and given him **Maintain** access to https://github.com/ros-gbp/teleop_twist_joy-release (I don't have rights to add him to the ros-teleop group there, or I just couldn't find out how).

**Comment by tonybaltovski** [comment]
Thanks @efernandez, I will wait for that access but I think @vincentrou's PR addresses the Noetic release for now.

**Comment by tonybaltovski** [comment]
Closing since https://github.com/ros/rosdistro/pull/26555 was merged for Noetic.
